equinor/appsec

docs/resources/learning-material.md, docs/security-champion/events/sc-kickoff-agenda.md, docs/security-champion/success-stories/index.md
=> Page for sc success stories

docs/security-champion/faq.md
closes https://github.com/equinor/isc-appsec/issues/306
=> Security Champion FAQ

docs/security-champion/getting-in-touch.md
=> added appsec representative information

docs/security-champion/useful-links.md
Closes https://github.com/equinor/isc-appsec/issues/305
=> Added useful links for SCs

mkdocs.yml, overrides/main.html, requirements.txt
closes https://github.com/equinor/isc-appsec/issues/357
=> Add Cookie information to appsec site

.github/workflows/azure-static-webapp.yml
Deploys here: https://gray-pebble-09faddd03.2.azurestaticapps.net/
=> Add azure static webapp action

docs/snyk/3-snyk_support.md, docs/snyk/guidelines/index.md
=> Create starting page for guidelines

docs/snyk/4-vulnerabilities.md
Intended as documentation when reaching out to teams regarding high and critical vulnerabilities
=> Add triaging requirement for snyk vulns

docs/assets/css/mkdocs-eq.css, docs/threat-modeling/resources/zgamified.md, mkdocs.yml
A change in MKdocs have made our green bare blue. This pr should fix the problem.
I also remove a ref to a missing/non-existent png for eop_gameplay
=> Fix styling, green bar

docs/security-champion/faq.md
Updating the FAQ for Security Champions, making the question a bit more up-to-date and adding some additional questions.
I tried scanning Slack to see if there were any re-occurring questions from there, but could not find any.
Resolves #99.
=> docs(security champion): update faq.md

docs/guidelines/index.md, docs/guidelines/postman.md
resolves #865 - Create guidelines on Postman and secrets in their cloud.
=> Postman guidelines

SECURITY.md
will add security.md file to abide by the new policy
=> add security md

mkdocs.yml, requirements.txt
Adds a plugin to show "last updated" for our pages
=> add last updated to pages

docs/threat-modeling/index.md
Adding a link to the TM public repo and GH Pages slides
=> Add linkt to tm repo and slides

docs/guidelines/secret-scanning.md
https://github.com/equinor/isc-appsec/issues/977
Added a section about GH-AS in the secret scanning guidelines.
=> GitHub advanced security secret scanning

docs/security-champion/events/2024/1-sc-meetup-3.md
docs(meetup): add agenda march 2024
=> docs(meetup): add agenda march 2024

docs/guidelines/gh-actions-runners.md, docs/guidelines/git-github.md, docs/guidelines/git-signed-commits.md
- generally fix small typos in newly added guidelines
=> docs: fix typos and re-phrase some places

mkdocs.yml
Adding navigation footer for #82. It may make the rendering on narrow screen a bit better.
=> Add navigation footer

.gitignore, .idea/.gitignore, docs/guidelines/FAQ/pre-commit-faq.md
Note of adding pre-commit to PATH after installation.
=> docs(guidelines): pre-commit note for adding to path after install

docs/guidelines/postman.md
Reading through the guidelines once more with "fresh eyes". Updating typos and trying to make things a bit more clear/to the point.
Overall, nothing in the guidelines themselves are changed.
=> docs(postman): refine guidelines

docs/security-champion/4-learning-platform.md
Remove the PR activity until we align on requirements and how it should be handled.
=> docs: remove activity from secure code platform

docs/security-champion/stories/index.md
Did not double check mkdocs syntax, this should correct it to make bulletpoints
=> docs: correct wrong mkdocs syntax

docs/snyk/4-vulnerabilities.md, docs/snyk/curriculum/4-scan_results.md
Minor tweaking regarding the Snyk guides.
=> docs(snyk): update recommendations and add tips

docs/security-champion/5-belts-and-activities.md
Adding a new Activity: 
Assessing and addressing issues in Snyk to achieve a 0-issue dashboard.
=> docs(security champion): add address Snyk issue activity

docs/experimental/git-signed-commits-old.md, docs/experimental/git-signed-commits-young.md
For a 1 of april newsletter joke
=> add experimental guidelines

.github/dependabot.yml
update dependabot.yml to target the requirements.txt file present in the repo
=> ghas: add pip to dependabot.yml

.github/workflows/backstage-techdocs.yml
For some reason, `mkdocs` was not found when being asked to run. 
Adding install of all of `requirements.txt`
=> Add missing package in workflow

docs/toolbox/guidelines/secret-scanning.md
We have archived the appsec-fundamentals-secret-scanning workshop. Secret scanning guidelines is updated accordingly. Adjusting a few things around GHAS and TH
=> Upd secret scanning guidline

docs/toolbox/guidelines/screening-os-packages.md, docs/toolbox/guidelines/security-screening-os-packages.md
We are creating a guideline with some advice related to screening open source packages from a security perspective.
=> Create guideline for security screening open source packages
